# Generated by Django 6.0.4 on 2026-05-06 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_remove_blog_comments_comment_blog_alter_blog_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='desc',
            field=models.TextField(max_length=5000, verbose_name='Description'),
        ),
    ]
